name: Java Maven Build Container Reusable Workflow

# Trigger this workflow by a caller workflow
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string

# This worfklow builds a container image from a Java Maven project
jobs:
  build-container:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}

      # Set tag version as POM revision
      - name: Set POM revision
        if: github.event_name == 'release'
        run: sed -i -E 's/(<revision>).*(<\/revision>)/\1'${GITHUB_REF#refs/tags/}'\2/g' pom.xml

      # Set container image name
      - name: Set container image name
        run: echo ${{ github.repository }} | sed 's#.*/##' | sed 's#^#container_image_name=#' >> $GITHUB_ENV

      # Build container image
      - name: Build container image
        run: |
          ./mvnw -B --file pom.xml clean verify \
          -Pnative \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.tag=latest \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.name=${{ env.container_image_name }} \

