name: Java Maven Build Container Reusable Workflow

# Trigger this workflow by a caller workflow
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string

# This worfklow builds a container image from a Java Maven project
jobs:
  build-container:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}

      # Set tag version as POM revision
      - name: Set Artifact ID
        id: set-artifact-id
        run: echo "artifact_id=$(grep -m 1 '<artifactId>' pom.xml | sed -e 's/<artifactId>\(.*\)<\/artifactId>/\1/')" >> "$GITHUB_OUTPUT"

      # Build container image for release
      - name: Build container image
        if: github.event_name == 'release'
        run: |
          docker build --build-arg REVISION=${GITHUB_REF#refs/tags/} -t ${{ steps.set-artifact-id.outputs.artifact_id }}:${GITHUB_REF#refs/tags/}_${GITHUB_SHA:0:7} .

      # Build container image without release
      - name: Build container image
        if: github.event_name != 'release'
        run: |
          docker build -t ${{ steps.set-artifact-id.outputs.artifact_id }}:${GITHUB_SHA:0:7} .

      - name: docker image
        run: docker image
