name: Java Maven JUnit Reusable Workflow

# Trigger this workflow by a caller workflow
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string

# This worfklow runs JUnit tests on a Java Maven project
jobs:
  junit:
    runs-on: ${{ fromJson(inputs.runner) }}
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: maven

      # Run Maven unit tests with release tag
      - name: Run tests with Maven
        if: github.event_name == 'release'
        run: mvn -Drevision=${GITHUB_REF#refs/tags/} -B test --file pom.xml 

        # Run Maven unit tests without release tag
      - name: Run tests with Maven
        if: github.event_name != 'release'
        run: mvn -B test --file pom.xml 

      # Report test results to GitHub
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven JUnit test report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
