name: Java Maven Publish Container Reusable Workflow

# Trigger this workflow by a caller workflow
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string

# This worfklow publishes a container image from a Java Maven project
jobs:
  publish-container:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}

      # Set tag version as POM revision
      - name: Set POM revision
        run: sed -i -E 's/(<revision>).*(<\/revision>)/\1'${GITHUB_REF#refs/tags/}'\2/g' pom.xml

      # Set container variables from context (container registry, image name)
      - name: Set container variables
        run: |
          echo container_registry=${{ github.server_url }} | sed 's#https://#&containers.#' | sed 's~http[s]*://~~g' >> $GITHUB_ENV
          echo ${{ github.repository }} | sed 's#.*/##' | sed 's#^#container_image_name=#' >> $GITHUB_ENV

      # Log in to the Container registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.container_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Publish Container image to GitHub Container Registry
      - name: Publish container image
        run: |
          ./mvnw -B --file pom.xml clean package \
          -Pnative \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=${{ env.container_registry }} \
          -Dquarkus.container-image.tag=${GITHUB_REF#refs/tags/} \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.name=${{ env.container_image_name }} \
          -Dquarkus.jib.base-registry-username=${{ github.actor }} \
          -Dquarkus.jib.base-registry-password=${{ secrets.GITHUB_TOKEN }}

      # List contents of working directory
      - name: List working directory
        run: find . -path ./.git -prune  -o -print
