name: Java Maven Build Package Reusable Workflow

# Trigger this workflow by a caller workflow
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string

# This worfklow builds a package from a Java Maven project
jobs:
  build-package:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}

      # Build Maven files for release
      - name: Build with Maven
        if: github.event_name == 'release'
        run: ./mvnw package -Drevision=${GITHUB_REF#refs/tags/} --file pom.xml

      # Build Maven files without release
      - name: Build with Maven
        if: github.event_name != 'release'
        run: ./mvnw package --file pom.xml
